/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';

import React from 'react';

const Gameboy = () => {
  const { nodes } = useGLTF('models/gameboy.glb');
  return (
    <group dispose={null}>
      {/* Gameboy */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboy.geometry}
        material={nodes.gameboy.material}
      />

      {/* Gameboy - Screen Borer */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboyScreenBorder.geometry}
        material={nodes.gameboyScreenBorder.material}
        position={nodes.gameboyScreenBorder.position}
        scale={nodes.gameboyScreenBorder.scale}
      />

      {/* Gameboy - Screen */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboyScreen.geometry}
        material={nodes.gameboyScreen.material}
        position={nodes.gameboyScreen.position}
        scale={nodes.gameboyScreen.scale}
      />

      {/* Gameboy - JoyStick */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboyJoystick.geometry}
        material={nodes.gameboyJoystick.material}
        position={nodes.gameboyJoystick.position}
        scale={nodes.gameboyJoystick.scale}
      />

      {/* Gameboy - A */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboyA.geometry}
        material={nodes.gameboyA.material}
        position={nodes.gameboyA.position}
        scale={nodes.gameboyA.scale}
      />

      {/* Gameboy - B */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboyB.geometry}
        material={nodes.gameboyB.material}
        position={nodes.gameboyB.position}
        scale={nodes.gameboyB.scale}
      />

      {/* Gameboy - Start */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboyStart.geometry}
        material={nodes.gameboyStart.material}
        position={nodes.gameboyStart.position}
        rotation={nodes.gameboyStart.rotation}
        scale={nodes.gameboyStart.scale}
      />

      {/* Gameboy - Select */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboySelect.geometry}
        material={nodes.gameboySelect.material}
        position={nodes.gameboySelect.position}
        rotation={nodes.gameboySelect.rotation}
        scale={nodes.gameboySelect.scale}
      />

      {/* Gameboy - Battery */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gameboyBattery.geometry}
        material={nodes.gameboyBattery.material}
        position={nodes.gameboyBattery.position}
        scale={nodes.gameboyBattery.scale}
      />
    </group>
  );
};

useGLTF.preload('models/gameboy.glb');

export default Gameboy;
